project_name: hystrix_exporter
release:
  github:
    owner: mdavydau
    name: hystrix_exporter
builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  env:
  - CGO_ENABLED=0
archive:
  files:
  - config.yml
dockers:
- image_templates:
  - 'caninjas/hystrix_exporter:latest'
  extra_files:
    - config.yml
